// src/lib/components/ProjectCard.svelte
<script context="module" lang="ts">
  import Card from "./Card.svelte";
  import ProjectImage from "./ProjectImage.svelte";
</script>

<script lang="ts">
  import { formatReleaseDate } from "$lib/formatDate";
  import type { Project } from "$lib/Project";

  export let project: Project;
  $: image = project.image;
</script>

<Card>
  <h1>{project.title}</h1>
  {#if image}
    <ProjectImage
      src={image.src}
      width={image.width}
      height={image.height}
      alt={image.alt}
    />
  {/if}
  {@html project.content}
  <div class="project-card__footer">
    <a href="/portfolio">&lt; Terug naar portfolio</a>
    <span class="project-card__release-date">
      {formatReleaseDate(project.released)}
    </span>
  </div>
</Card>

<style lang="scss">
  .project-card__footer {
    display: flex;
    justify-content: space-between;
  }
  .project-card__release-date {
    color: #aaa;
  }
</style>

// components/ProjectCard.vue
<template>
  <Card>
    <nuxt-link to="/portfolio">&lt; Terug naar portfolio</nuxt-link>
    <h1 class="h2">{{ project.title }}</h1>
    <img v-if="project.image" :src="'https://bfanger.nl/thumbs/660w/' + project.image" class="project-card__image">
    <div v-html="project.description"/>
  </Card>
</template>

<script>
import Card from "./Card.vue";
export default {
  components: { Card },
  props: {
    project: { type: Object, required: true }
  }
};
</script>

<style lang="scss">
.project-card__image {
  display: block;
  max-width: 100%;
  margin-bottom: 1em;
}
</style>
