// src/routes/portfolio/+page.svelte
<script lang="ts">
  import Page from "$lib/components/Page.svelte";
  import Card from "$lib/components/Card.svelte";
  import NavButton from "$lib/components/NavButton.svelte";
  import Disclaimer from "$lib/components/Disclaimer.svelte";
  import cardTransition, {
    cardIn,
    cardOut,
  } from "$lib/services/cardTransition";
  import { groupBy } from "lodash-es";
  import type { PageData } from "./$types";

  export let data: PageData;

  type Teaser = PageData["teasers"][number];

  $: grouped = groupBy(data.teasers, extractYear) as Record<string, Teaser[]>;
  $: years = Object.keys(grouped).sort().reverse();

  function extractYear(project: Teaser) {
    const match = project.released.toString().match(/^[0-9]+/);
    if (match === null) {
      console.warn(`Project[${project.slug}].released is invalid`); // eslint-disable-line no-console
      return 2000;
    }
    return parseInt(match[0], 10);
  }
</script>

<svelte:head>
  <title>Bob Fanger's portfolio</title>
</svelte:head>
<Page>
  <div in:cardIn={{}} out:cardOut={{}}>
    <Card>
      <h1>Portfolio van Bob Fanger</h1>
      {#each years as year}
        <h2>{year}</h2>
        <ul
          on:mousedown={() => {
            cardTransition.set("left");
          }}
        >
          {#each grouped[year] as project}
            <li>
              <a href="projects/{project.slug}">{project.title}</a>
            </li>
          {/each}
        </ul>
      {/each}
      <slot />
    </Card>
  </div>
  <div class="previous">
    <NavButton
      href="/"
      type="previous"
      on:mousedown={() => {
        cardTransition.set("right");
      }}
    >
      Home
    </NavButton>
  </div>
  <Disclaimer />
</Page>

<a hidden href="/scrollytelling/bfanger.nl-v3">poc</a>

<style lang="scss">
  .previous {
    position: fixed;

    bottom: calc(50% - 35px);
    left: calc(50vw - 550px);
    transform: translateX(-50%);
    @media (max-width: 1290px) {
      left: 30px;
      transform: none;
    }
    @media (max-width: 880px) {
      bottom: 40px;
      left: 40px;
    }
  }
</style>

// pages/portfolio.vue
<template>
  <div>
    <NavButton 
      to="/" 
      type="previous"
      class="portfolio__previous">Home</NavButton>
    <Card>
      <h1>Portfolio van Bob Fanger</h1>
      <div 
        v-for="{year, projects} in projectsByYear" 
        :key="year">
        <h2>{{ year }}</h2>
        <ul>
          <li 
            v-for="project in projects" 
            :key="project.slug">
            <nuxt-link :to="'projects/' + project.slug">{{ project.title }}</nuxt-link>
          </li>
        </ul>
      </div>
    </Card>
    <ProjectDisclaimer/>
  </div>
</template>

<script>
import { mapGetters } from "vuex";
import Card from "../components/Card.vue";
import ProjectDisclaimer from "../components/ProjectDisclaimer.vue";
import NavButton from "../components/NavButton.vue";

export default {
  components: { Card, ProjectDisclaimer, NavButton },
  head() {
    return {
      title: "Bob Fanger's portfolio",
      link: [
        { rel: "cannonical", href: `https://bfanger.nl${this.$route.path}` }
      ]
    };
  },
  computed: {
    ...mapGetters({
      projectsByYear: "projects/groupedByYear"
    })
  },
  async fetch({ store }) {
    await store.dispatch("projects/fetchAll");
  }
};
</script>

<style lang="scss">
.portfolio__previous {
  position: fixed;
  bottom: calc(50% -35px);
  left: calc(50vw - 550px);
  transform: translateX(-50%);
  @media (max-width: 1290px) {
    left: 30px;
    transform: none;
  }
  @media (max-width: 880px) {
    bottom: 40px;
    left: 40px;
    // transform: translateX(-50%);
  }
}
</style>
